export const getAllProducts = [
  {
    id: 1,
    image: '/products/kikiriki-puter.png',
    title: 'Kikiriki puter',
    currentPrice: 870,
    oldPrice: 990,
    weight: '750 g',
  },
  {
    id: 2,
    image: '/products/zejtin.png',
    title: 'Zejtin',
    currentPrice: 150,
    oldPrice: 175,
    weight: '1 l',
  },
  {
    id: 3,
    image: '/products/suncokretov-puter.png',
    title: 'Suncokretov puter',
    currentPrice: 520,
    oldPrice: 860,
    weight: '750 g',
  },
  {
    id: 4,
    image: '/products/laneno-ulje.png',
    title: 'Laneno ulje',
    currentPrice: 1100,
    oldPrice: 1310,
    weight: '250 ml',
  },
  {
    id: 5,
    image: '/products/zejtin.png',
    title: 'Zejtin',
    currentPrice: 150,
    oldPrice: 175,
    weight: '1 l',
  },
  {
    id: 6,
    image: '/products/kokosov-protein.png',
    title: 'Kokosov protein',
    currentPrice: 1600,
    oldPrice: 2100,
    weight: '750 g',
  },
  {
    id: 7,
    image: '/products/rogac-agava.png',
    title: 'Naturela sa Rogačem i Agava Šećerom',
    currentPrice: 546,
    oldPrice: 650,
    weight: '750 g',
  },
  {
    id: 8,
    image: '/products/suncokretov-puter.png',
    title: 'Suncokretov puter',
    currentPrice: 520,
    oldPrice: 860,
    weight: '750 g',
  },
  {
    id: 9,
    image: '/products/rogac-agava.png',
    title: 'Naturela sa Rogačem i Agava Šećerom',
    currentPrice: 546,
    oldPrice: 700,
    weight: '750 g',
  },
  {
    id: 10,
    image: '/products/cokolada-sumsko-voce.png',
    title: ' Proteinske čokoladica sa šumskim voćem',
    currentPrice: 630,
    oldPrice: 790,
    weight: '30 g',
  },
  {
    id: 11,
    image: '/products/laneno-ulje.png',
    title: 'Laneno ulje',
    currentPrice: 1100,
    oldPrice: 1310,
    weight: '250 ml',
  },
  {
    id: 12,
    image: '/products/kikiriki-puter.png',
    title: 'Kikiriki puter',
    currentPrice: 870,
    oldPrice: 990,
    weight: '750 g',
  },
  {
    id: 13,
    image: '/products/cokolada-sumsko-voce.png',
    title: ' Proteinske čokoladica sa šumskim voćem',
    currentPrice: 630,
    oldPrice: 790,
    weight: '30 g',
  },
  {
    id: 14,
    image: '/products/rogac-agava.png',
    title: 'Naturela sa Rogačem i Agava Šećerom',
    currentPrice: 546,
    oldPrice: 700,
    weight: '750 g',
  },
  {
    id: 15,
    image: '/products/kokosov-protein.png',
    title: 'Kokosov protein',
    currentPrice: 1600,
    oldPrice: 2100,
    weight: '750 g',
  },
  {
    id: 16,
    image: '/products/suncokretov-puter.png',
    title: 'Suncokretov puter',
    currentPrice: 520,
    oldPrice: 860,
    weight: '750 g',
  },
];
